# dockerfile to setup and intall fekan. Useful for e.g benchmarking with AWS Batch
FROM rustlang/rust:nightly

# Install necessary tools
RUN apt-get update && apt-get install -y \
    git \
    awscli \
    python3-venv \
    python3-pip

COPY src /fekan/src
COPY Cargo.toml /fekan/Cargo.toml
COPY benches /fekan/benches

WORKDIR /fekan

# Install fekan
RUN cargo install --path . --features serialization

WORKDIR /fekan/benches

RUN python3 -m venv /venv 

ENV PATH="/venv/bin:${PATH}"

# RUN pip3 install --upgrade pip && \
#     pip3 install -r requirements.txt


