
FROM rustlang/rust:nightly

# Install necessary tools
RUN apt-get update && apt-get install -y \
    git \
    awscli \
    python3-venv \
    python3-pip

RUN python3 -m venv /venv 

ENV PATH="/venv/bin:${PATH}"